blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from generator import views as generator_views
from todo import views as toto_views
from portfolio import views 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    
    # blog
    path('blog/', include('blog.urls')),
    
    # password generator
    path('generator/', generator_views.generator, name='generator'),
    path('password/', generator_views.password, name='password'),
    
    # contact
    path('contact/', views.contact, name='contact'),

    # auth
    path('signup/', toto_views.signupuser, name='signupuser'),
    path('login/', toto_views.loginuser, name='loginuser'),
    path('logout/', toto_views.logoutuser, name='logoutuser'),

    # todo
    path('todolist', toto_views.todolist, name='todolist'),
    path('create/', toto_views.createtodo, name='createtodo'),
    path('current/', toto_views.currenttodos, name='currenttodos'),
    path('completed/', toto_views.completedtodos, name='completedtodos'),
    path('todo/<int:todo_pk>', toto_views.viewtodo, name='viewtodo'),
    path('todo/<int:todo_pk>/complete', toto_views.completetodo, name='completetodo'),
    path('todo/<int:todo_pk>/delete', toto_views.deletetodo, name='deletetodo'),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/', height_field=None, width_field=None, max_length=None)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

class Messages(models.Model):
    created = models.DateField(auto_now_add=True)
    subject = models.CharField(max_length=250)
    message = models.TextField(blank=True)
    from_email = models.CharField(max_length=250)
    
    def __str__(self):
        return self.subject
    

portfolio/forms.py
from django.forms import ModelForm
from .models import Messages

class MessageForm(ModelForm):
    class Meta:
        model = Messages
        fields = ['subject', 'message', 'from_email']

portfolio/views.py
from django.shortcuts import render
from .models import Project, Messages
from .forms import MessageForm
from django.core.mail import send_mail

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects':projects })

def contact(request):
    if request.method == 'GET':
        return render(request, 'portfolio/contact.html', {'form':MessageForm()})
    else:
        try:
            form = MessageForm(request.POST or None)
            form.save()
            # send email
            send_mail(
                'Personal Website' + '-' + request.POST['subject'], # subject
                'Message from: ' + request.POST['from_email'] + ' Message: ' +  request.POST['message'], # message
                request.POST['from_email'], # from email
                ['martinczarkowski@gmail.com'], # to email
                fail_silently=False,
            )
            return render(request, 'portfolio/contact.html', {'message':form})
        except ValueError:
            return render(request, 'portfolio/contact.html', {'error':MessageForm(), 'error':'Something is whong. Try again!'})
        
        

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
  <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

  <title>Martin Czarkowski</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Martin's Logo">
        <span>Martin Czarkowski</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Curriculum Vitae</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% static "portfolio/cv_czarkowski_en.pdf" %}" target="_blank">EN</a>
              <a class="dropdown-item" href="{% static "portfolio/cv_czarkowski_cz.pdf" %}" target="_blank">CZ</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/martin-czarkowski-4252828b/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/martinczarkowski" target="_blank">GitHub</a>
          </li>
           <li class="nav-item">
            <a class="nav-link" href="/contact">Contact</a>
          </li>
          <!--li class="nav-item">
            <a class="nav-link" href="https://twitter.com/" target="_blank">Twitter</a>
          </li-->
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

<footer class="footer mt-auto py-3 text-center">
  <div class="container">
     <p class="mb-0">This page is created with Python Django 3, HTML5, CSS3 and Bootstrap 4</p>
    <span class="text-muted">© 2021 Copyright:<a href="https://martinczarkowski.pythonanywhere.com"> martinczarkowski.pythonanywhere.com</a></span>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="../assets/dist/js/bootstrap.bundle.js"></script></body>

</html>

portfolio/templates/portfolio/contact.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center mb-3">
  <div class="col-md-20 text-center">
    <h1 id="hometext" class="font-weight-bold">Get In Touch!</h1>
    <b>Mobile</b>: <a href="tel:+420739942385">+420 739 942 385</a><br>
    <b>Email</b>: <a href = "mailto: martinczarkowski@gmail.com">martinczarkowski@gmail.com</a><br>
    <b>Web</b>: <a href = "https://martinczarkowski.pythonanywhere.com/">www.martinczarkowski.com</a><br>
    <b>Address</b>: 639-00 Brno, Czech republic
    <br>
    
    <a href = "https://www.linkedin.com/in/martin-czarkowski-4252828b/" target="_blank">LinkedIn</a>
    <a href = "https://github.com/martinczarkowski" target="_blank">GitHub</a>

  </div>
</div>

{% if message %}

<div class="row justify-content-center mb-3">
  <div class="col-md-20 text-center">
    <div class="alert alert-success" role="alert">
      <h1>Thanks for your message</h1> I will reply as soon as possible!
    </div>
  </div>
</div>
{% else %}
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
        {% endif %}
            <div class="col-md-15 text-center">
              <h2>Want to chat? Contact me here</h5>
            </div>
            <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <input type="text" name="subject" class="form-control" id="subject" placeholder="Your Name">
            </div>
            <div class="form-group">
              <input type="email" name="from_email" class="form-control" id="from_email" placeholder="Your Email">
            </div>
            <div class="form-group">
              <textarea class="form-control" name="message" id="message" rows="5" placeholder="Your Message"></textarea >
            </div>
            <div class="col-md-15 text-center">
              <button type="submit" class="btn btn-primary">Send Message</button>
            </div>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-4">
    <img src="{% static 'portfolio/me.jpg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-20 text-center">
    <h1 id="hometext" class="font-weight-bold"> Hi, I’m Martin! </h1>
    <h2 class="mt-5">I love sports, dance, music, technology and my beatiful daughter!</h2><br>
    <p> 
    I was born in Brno Czech Republic and I also live and work here. It's the best place to live!
    I have been working as a software developer for several years (T-SQL, PL/SQL, PL/pgSQL) at TietoEVRY
    </p>
    <p>
    I enjoy working with these technologies PostreSQL - PL/pgSQL, Oracle - PL/SQL, MS SQL SERVER, Python - Django, GIT, TFS, Jira, Confluence, Fedora
    </p>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}